### ISSUE TITLE
Status + FLOSS driver/controller

### ISSUE THREAD

**Issue by enricostano** [OSE/CNC-Torch-Table-OSE#25]
Hi there,

what's the status of this project? I'm interested in FLOSS driver/controller for CNC and would be nice to have more info.

Do you still have plans to work upon the Lasersaur controller? Any result to share?

Many thanks!

**Comment by Fractal618** [comment]
Hi Enrico,

I haven't been involved in this for quite some time, but I will private message you some contacts that I was working with.

I am happy to see interest in this project, and will help however I can .

Chris
